name: Shell Commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World, this is my first github Workflow"
      - name: multiline script
        run: |
          node -v
          npm -v
          cat /etc/os-release
      - name: show RAM
        run: free -h
      - name: show IP
        run: ifconfig
      - name: environment variables
        run: printenv
      - name: python command
        run: |
          import platform
          print
          (platform.processor())
        shell: python
  runs-windows-command:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: echo
        run: echo "Hello this is happening on powershell"
      - name: directory powershell
        run: get-location
      - name: directory bash
        run: pwd    
        shell: bash 
      - name: show OS details
        run: systeminfo
        